package com.keheck.logicBlox;

import com.keheck.logicBlox.init.SmeltingInit;
import com.keheck.logicBlox.proxy.ClientProxy;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import static com.keheck.logicBlox.Main.MODID;
import static com.keheck.logicBlox.Main.VERSION;

@Mod(modid = MODID, version = VERSION)
public class Main
{
    @Mod.Instance
    public static Main instance;

    public static final String MODID = "logicblox";
    public static final String VERSION = "1.0";

    @SidedProxy(clientSide = "com.keheck.logicBlox.proxy.ClientProxy", serverSide = "com.keheck.logicBlox.proxy.CommonProxy")
    public static ClientProxy proxy;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.modId = MODID;
        data.version = VERSION;
        data.authorList.add("Keheck");
        data.credits = "";
        data.description = "This mod adds blocks that work as logic gates, so you don't have to build them yourself";
        data.name =  "Logic Blox 1.12.2";
        data.url = "https://minecraft.curseforge.com/projects/logic-blox";
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event)
    {
        SmeltingInit.recipes();
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {

    }
}
